version: '3.4'

services:
  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    ports:
      - 9080:8080
    restart: always

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    hostname: mariadb
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD:-nopassword}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-voucher}"
      MYSQL_USER: "${MYSQL_USER:-voucher}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-nopassword}"
    restart: on-failure
    volumes:
      - mariadb-data:/var/lib/mysql:rw
      - ./mariadb/fixtures:/docker-entrypoint-initdb.d:ro,delegated

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER:-voucher}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS:-voucher}"
    restart: always
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    hostname: nginx
    build:
      context: ./app
      target: nginx
      args:
        HOST_UID: "${HOST_UID:-33}"
        HOST_GID: "${HOST_GID:-33}"
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    depends_on:
      - app
    volumes:
      - ./app/docker/nginx/certs:/etc/nginx/certs:ro,delegated
      - ./app/public:/srv/app/public:ro,delegated

  app:
    image: php:7.4-fpm-alpine
    container_name: app
    hostname: app
    build:
      context: ./app
      target: app
      args:
        HOST_UID: "${HOST_UID:-33}"
        HOST_GID: "${HOST_GID:-33}"
    environment:
      PHP_DATE_TIMEZONE: "${PHP_DATE_TIMEZONE:-UTC}"
      OPCACHE_VALIDATE_TIMESTAMPS: "${OPCACHE_VALIDATE_TIMESTAMPS:-0}"
      DATABASE_URL: "mysql://${MYSQL_USER:-voucher}:${MYSQL_PASSWORD:-nopassword}@mariadb:3306/${MYSQL_DATABASE:-voucher}"
      MESSENGER_TRANSPORT_DSN: "amqp://${RABBITMQ_USER:-voucher}:${RABBITMQ_PASS:-voucher}@rabbitmq:5672/%2f/messages"
    restart: always
    depends_on:
      - rabbitmq
      - mariadb
    volumes:
      - ./app:/srv/app:rw,cached
      - ./app/var:/srv/app/var:rw,delegated
      - ./app/public:/srv/app/public:rw,delegated

volumes:
  mariadb-data:
    driver: local
  rabbitmq-data:
    driver: local
