monolog:
  handlers:
    main:
      type: group
      members: [logfile]
    logfile:
      type: stream
      level: debug
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      channels: ['!event']
      #channels: ['!event', '!doctrine']
    stdout:
      type: stream
      level: info
      path: 'php://stdout'
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!console", "!doctrine", "!event", "!messenger"]
    # uncomment to get logging in your browser
    # you may have to allow bigger header sizes in your Web server configuration
    #firephp:
    #    type: firephp
    #    level: info
    #chromephp:
    #    type: chromephp
    #    level: info
